
/*
 *  =================================================================
 *
 *    26.03.20   <--  Date of Last Modification.
 *                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 *  -----------------------------------------------------------------
 *
 *  **** Module  :  js-common/tasks/common.tasks.imosflm.js
 *       ~~~~~~~~~
 *  **** Project :  jsCoFE - javascript-based Cloud Front End
 *       ~~~~~~~~~
 *  **** Content :  iMosflm Task Class (for local server)
 *       ~~~~~~~~~
 *
 *  (C) E. Krissinel, A. Lebedev 2019-2020
 *
 *  =================================================================
 *
 */

'use strict';

var __template = null;

if (typeof module !== 'undefined' && typeof module.exports !== 'undefined')
  __template = require ( './common.tasks.template' );

// ===========================================================================

function TaskIMosflm()  {

  if (__template)  __template.TaskTemplate.call ( this );
             else  TaskTemplate.call ( this );

  this._type   = 'TaskIMosflm';
  this.name    = 'iMosflm (image processing)';
  this.setOName ( 'imosflm' );  // default output file name template
  this.title   = 'Interactive Image Processing with iMosflm';
  //this.helpURL = './html/jscofe_task_imosflm.html';
  this.nc_type = 'client';  // job may be run only on client NC

  this.input_dtypes = [];   // no input data for this task

  this.parameters = {       // no input parameters, just label
    L1 : { type     : 'label',
           label    : '<h3>This task will launch iMosflm on your computer.</h3>',
           position : [0,0,1,1]
         },
    L2 : { type     : 'label',
           label    : 'When iMosflm session is finished (Session &gt;' +
                      ' Exit or main window closed):<br><ul>' +
                      '<li>unmerged data files stored in the default' +
                      ' location will be imported</li>' +
                      '<li>unmerged data files stored in a custom' +
                      ' location will NOT be imported</li>' +
                      '<li>merged data files generated by Quick Scale' +
                      ' will NOT be imported<br></li></ul>',
           position : [1,0,1,1]
         }
  };

}


if (__template)
      TaskIMosflm.prototype = Object.create ( __template.TaskTemplate.prototype );
else  TaskIMosflm.prototype = Object.create ( TaskTemplate.prototype );
TaskIMosflm.prototype.constructor = TaskIMosflm;


// ===========================================================================
// export such that it could be used in both node and a browser

TaskIMosflm.prototype.icon = function()  { return 'task_imosflm'; }

TaskIMosflm.prototype.lowestClientVersion = function() { return '1.6.001 [01.01.2019]'; }

TaskIMosflm.prototype.currentVersion = function()  {
  var version = 0;
  if (__template)
        return  version + __template.TaskTemplate.prototype.currentVersion.call ( this );
  else  return  version + TaskTemplate.prototype.currentVersion.call ( this );
}

if (!__template)  {
  //  for client side

  TaskIMosflm.prototype.onJobDialogStart = function ( job_dialog )  {
    job_dialog.run_btn.click();  // start automatically
  }

} else  {
  //  for server side

  var conf = require('../../js-server/server.configuration');

  TaskIMosflm.prototype.getCommandLine = function ( jobManager,jobDir )  {
    return [conf.pythonName(), '-m', 'pycofe.tasks.imosflm', jobManager, jobDir, this.id];
  }

  // -------------------------------------------------------------------------

  module.exports.TaskIMosflm = TaskIMosflm;

}
